services:
  api:
    build: ./backend        
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend

  web:
    build: ./frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/frontend

