# Generated by Django 5.1.4 on 2024-12-28 04:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_remove_ticket_email_remove_ticket_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="temp_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
