# Generated by Django 5.1.4 on 2024-12-28 04:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_ticket_temp_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="id",
        ),
        migrations.AlterField(
            model_name="ticket",
            name="temp_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
