# Generated by Django 5.1.4 on 2024-12-28 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0004_remove_ticket_id_alter_ticket_temp_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="temp_id",
            new_name="id",
        ),
    ]
