# Generated by Django 5.1.4 on 2025-01-12 16:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0005_rename_temp_id_ticket_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="screenshot_links",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=500),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
